
const cuteNames = [
    'Slimy',
    'Slimey',
    'Slick',
    'Slinky',
    'Shelldon',
    'Shellen',
    'Slugoton',
    'Slugette',
    'Shellsworth',
    'Sluggie',
    'Shellby',
    'Shellton',
    'Snaily',
    'Snello',
    'Snella',
    'Snellie',
    'Snella',
    'Snello',
    'Snailbert',
    'Snailo',
    'Snailina',
    'Shellsford',
    'Snailford',
    'Shellsley',
    'Snailsley',
    'Sluggo',
    'Shellsworth',
    'Snailsworth',
    'Slugworth',
    'Shellsworth',
    'Snailworth',
    'Slugster',
    'Shellster',
    'Snailster',
    'Slim',
    'Slimy',
    'Slimerton',
    'Slimer',
    'Slimina',
    'Slimerina',
    'Slimo',
    'Slim',
    'Slime',
    'Slimina',
    'Slimey',
    'Slimella',
    'Slimello',
    'Slimey',
    'Slugger',
    'Sluggy',
    'Sluggerina',
    'Sluggy',
    'Slugette',
    'Slugo',
    'Slugon',
    'Slugsworth',
    'Sluggly',
    'Sluggerton',
    'Sluggina',
    'Slugglon',
    'Sluggles',
    'Slugglina',
    'Slugglie',
    'Shellby',
    'Shellerton',
    'Shelley',
    'Shellina',
    'Shello',
    'Shellton',
    'Shellsworth',
    'Shellton',
    'Shellworth',
    'Shelley',
    'Shellina',
    'Shello',
    'Shellton',
    'Shellsworth',
    'Shellsworth',
    'Shellsworth',
    'Snello',
    'Snella',
    'Snellie',
    'Snella',
    'Snello',
    'Snailbert',
    'Snailo',
    'Snailina',
    'Snailford',
    'Snailsley',
    'Snailworth',
    'Snailster',
    'Snailworth',
    'Snailster',
    'Snailo',
    'Snailina',
    'Snailford',
    'Snailsworth',
    'Snailina',
    'Snailo',
    'Snailbert',
    'Snailford',
    'Snailsworth',
    'Snailworth',
    'Snailster',
    'Slimerton',
    'Slimerina',
    'Slimer',
    'Slimina',
    'Slimo',
    'Slim',
    'Slime',
    'Slimina',
    'Slimey',
    'Slimella',
    'Slimello',
    'Slimey',
    'Slugger',
    'Sluggy',
    'Sluggerina',
    'Sluggy',
    'Slugette',
    'Slugo',
    'Slugon',
    'Slugsworth',
    'Sluggly',
    'Sluggerton',
    'Sluggina',
    'Slugglon',
    'Sluggles',
    'Slugglina',
    'Slugglie',
    'Slimer',
    'Slimina',
    'Slimerina',
    'Slimo',
    'Slime',
    'Slimey',
    'Slimella',
    'Slimello',
    'Snaily',
    'Slimey',
    'Slugger',
    'Sluggy',
    'Sluggerina',
    'Sluggy',
    'Slugette',
    'Slugo',
    'Slugon',
    'Slugsworth',
    'Sluggly',
    'Sluggerton',
    'Sluggina',
    'Slugglon',
    'Sluggles',
    'Slugglina',
    'Slugglie',
    'Snelly',
    'Snello',
    'Snella',
    'Snellie',
    'Snella',
    'Snello',
    'Snailbert',
    'Snailo',
    'Snailina',
    'Snailford',
    'Snailsley',
    'Snailworth',
    'Snailster',
    'Slimey',
    'Slimy',
    'Slick',
    'Slinky',
    'Shelldon',
    'Shellen',
    'Slugoton',
    'Slugette',
    'Shellsworth',
    'Sluggie'
  ];

  const rpgItems = [
    'Sword',
    'Axe',
    'Shield',
    'Dagger',
    'Spear',
    'Mace',
    'Crossbow',
    'Bow',
    'Quiver',
    'Helmet',
    'Armor',
    'Bracers',
    'Gauntlets',
    'Boots',
    'Cloak',
    'Ring',
    'Amulet',
    'Medallion',
    'Talisman',
    'Crown',
    'Scepter',
    'Wand',
    'Staff',
    'Book',
    'Scroll',
    'Map',
    'Compass',
    'Spyglass',
    'Telescope',
    'Torch',
    'Lantern',
    'Candle',
    'Matches',
    'Rope',
    'Grappling Hook',
    'Pickaxe',
    'Potion',
    'Elixir',
    'Oil',
    'Antidote',
    'Holy Water',
    'Herbs',
    'Spices',
    'Incense',
    'Lotion',
    'Salve',
    'Incantation',
    'Totem',
    'Gem',
    'Jewel',
    'Crystal',
    'Charm',
    'Idol',
    'Statuette',
    'Relic',
    'Artifact',
    'Figurine',
    'Goblet',
    'Bag',
    'Crate',
    'Chest',
    'Urn',
    'Box',
    'Vial',
    'Flask',
    'Bottle',
    'Jar',
    'Key',
    'Lockpick',
    'Pouch',
    'Canteen',
    'Flute',
    'Harp',
    'Drum',
    'Horn',
    'Trumpet',
    'Bugle',
    'Bell',
    'Whistle',
    'Instrument',
    'Tool',
    'Trap',
    'Ladder',
    'Grappling Iron',
    'Lantern Oil',
    'Chalk',
    'Ink',
    'Quill',
    'Parchment',
    'Scroll Case',
    'Spyglass Case',
    'Telescope Case',
    'Clothing',
    'Shoes',
    'Hat',
    'Gloves',
    'Food',
    'Water',
    'Cup',
    'Bowl',
    'Plate',
    'Spoon',
    'Fork',
    'Knife',
    'Tinderbox',
    'Coin Purse',
    'Coin Pouch',
    'Money Bag',
    'Money Belt',
    'Coin',
    'Gold',
    'Silver',
    'Bronze',
    'Copper',
    'Potion Belt',
    'Gem Pouch',
    'Jewelry Box',
    'Backpack',
    'Satchel',
    'Rations',
    'Bedroll',
    'Hammer',
    'Saw',
    'Chisel',
    'Whetstone',
    'Screwdriver',
    'Pliers',
    'Crowbar',
    'Shovel',
    'Fishing Rod',
    'Net',
    'Bait',
    'Lure',
    'Hook',
    'Line',
    'Sling',
    'Ammunition',
    'Arrow',
    'Quarrel',
    'Bolt',
    'Stone',
    'Knapsack',
    'Decanter',
    'Hourglass',
    'Censer',
    'Perfume',
    'Mirror',
    'Mask',
    'Cloak Pin',
    'Lock',
    'Seal',
    'Potion Flask',
    'Trap Component',
    'Tinder',
    'Holy Symbol',
    'Sacrificial Dagger',
    'Focusing Lens',
    'Arcane Focus',
    'Divining Rod',
    'Knife Sheath',
    'Shuriken',
    'Kunai',
    'Dart',
    'Lightning Rod',
    'Rapier',
    'Halberd',
    'Maul',
    'Greatsword',
    'Warhammer',
    'Down Quill',
    'Feather Pen',
    'Inkwell',
    'Painting',
    'Statue',
    'Tapestry',
    'Carpet',
    'Brazier',
    'Barrel',
    'Cask',
    'Jug',
    'Keg',
    'Spyglass Lens',
    'Telescope Lens',
    'Spyglass Tube',
    'Telescope Tube',
    'Spyglass Mount',
    'Telescope Mount',
    'Spyglass Stand',
    'Telescope Stand',
    'Goggles',
    'Monocle',
    'Spectacles',
    'Rag',
    'Cloth',
    'Towel',
    'Bucket',
    'Cauldron',
    'Pot',
    'Pan',
    'Ladle',
    'Spatula',
    'Frying Pan',
    'Spoon',
    'Fork',
    'Whisk',
    'Furnace',
    'Flint and Steel',
    'Hammer and Chisel',
    'Scroll Tube',
    'Map Case',
    'Compass Case',
    'Gemstone',
    'Jewel',
    'Orb',
    'Censer',
    'Divination Tool',
    'Holy Reliquary',
    'Holy Icon',
    'Holy Symbol',
    'Holy Relic',
    'Holy Script',
    'Holy Tome',
    'Holy Water Flask',
    'Holy Oil Flask',
    'Holy Elixir Flask',
    'Holy Incense Flask',
    'Holy Tea Flask',
    'Holy Salve Flask',
    'Holy Elixir',
    'Holy Oil',
    'Holy Incense',
    'Holy Tea',
    'Holy Salve',
    'Holy Statuette',
    'Holy Figurine',
    'Holy Idol',
    'Holy Charm',
    'Holy Amulet',
    'Holy Medallion',
    'Holy Talisman',
    'Holy Crown',
    'Holy Scepter',
    'Holy Wand',
    'Holy Staff',
    'Holy Book',
    'Holy Scroll',
    'Holy Map',
    'Holy Compass',
    'Holy Spyglass',
    'Holy Telescope',
    'Holy Torch',
    'Holy Lantern',
    'Holy Candle',
    'Holy Matches',
    'Holy Rope',
    'Holy Grappling Hook',
    'Holy Pickaxe',
    'Laser Shooting Bow',
  ];

  const adjectives = ['happy', 'sad', 'amused', 'angry', 'sleepy', 'jealous', 'bored', 'energetic', 'carefree', 'lively', 'cheerful', 'playful', 'lazy', 'tired', 'confident', 'fearless', 'anxious', 'nervous', 'content', 'determined', 'irritable', 'excited', 'affectionate', 'jovial', 'cranky', 'calm', 'grumpy', 'distracted', 'shy', 'bold', 'hopeful', 'surprised', 'timid', 'defiant', 'peaceful', 'strong', 'weak', 'relaxed', 'friendly', 'suspicious', 'aloof', 'curious', 'frightened', 'doubtful', 'sensitive', 'silly', 'pensive', 'gloomy', 'weary', 'lonely', 'satisfied', 'optimistic', 'cautious', 'dazzled', 'jubilant', 'envious', 'enraged', 'dismayed', 'distressed', 'awed', 'adventurous', 'admiring', 'amazed', 'ambitious', 'bewildered', 'blessed', 'brave', 'bright', 'capable', 'charmed', 'classic', 'colorful', 'concerned', 'courageous', 'crazy', 'creative', 'cruel', 'dark', 'delighted', 'diligent', 'drained', 'eager', 'elated', 'emotional', 'fanciful', 'foolish', 'forgetful', 'frightening', 'gleeful', 'grieving', 'groggy', 'guilty', 'hateful', 'helpful', 'hilarious', 'honorable', 'hungry', 'humble', 'imaginative', 'impulsive', 'independent', 'innocent', 'inquisitive', 'insecure', 'jolly', 'kind', 'loving', 'mysterious', 'mystified', 'obliging', 'pessimistic', 'proud', 'quizzical', 'realistic', 'regretful', 'remorseful', 'resigned', 'romantic', 'sarcastic', 'selfish', 'serious', 'shocked', 'shy', 'somber', 'stubborn', 'stunned', 'sympathetic', 'thankful', 'thoughtful', 'tough', 'unconcerned', 'unhappy', 'unique', 'uplifted', 'vigilant', 'wary', 'wicked', 'wise', 'zealous'];

  const colorCombinations = [
    'Red Striped',
    'Yellow Dotted',
    'Green Plaid',
    'Blue Checkered',
    'Purple Floral',
    'Orange Polka-Dot',
    'Gray Tartan',
    'Black Paisley',
    'White Striped',
    'Crimson Checked',
    'Teal Paisley',
    'Pink Plaid',
    'Lavender Floral',
    'Mint Polka-Dot',
    'Coral Tartan',
    'Maroon Checkered',
    'Lime Striped',
    'Sky Blue Dotted',
    'Magenta Paisley',
    'Indigo Plaid',
    'Lemon Floral',
    'Navy Polka-Dot',
    'Olive Tartan',
    'Salmon Checkered',
    'Mustard Striped',
    'Taupe Dotted',
    'Violet Paisley',
    'Beige Plaid',
    'Bronze Floral',
    'Khaki Polka-Dot',
    'Fuchsia Tartan',
    'Scarlet Checkered',
    'Aqua Striped',
    'Silver Dotted',
    'Mauve Paisley',
    'Peach Plaid',
    'Red Hearted',
    'Cyan Floral',
    'Brown Polka-Dot',
    'Golden Tartan',
    'Ivory Checkered',
    'Cream Striped',
    'Plum Dotted',
    'Sage Paisley',
    'Onyx Plaid',
    'Honey Floral',
    'Burgundy Polka-Dot',
    'Rust Tartan',
    'Navy Blue Checkered',
    'Charcoal Striped',
    'Blush Dotted',
    'Sandy Paisley',
    'Eggplant Plaid',
    'Mustard Yellow Floral',
    'Bubblegum Polka-Dot',
    'Forest Green Tartan'
];

module.exports = { cuteNames, adjectives, rpgItems, colorCombinations };